services:
  k-wave:
    image: simcore/services/comp/${IMAGE_TO_RUN}:${TAG_TO_RUN}
    environment:
      - INPUT_FOLDER=/tmp/inputs
      - OUTPUT_FOLDER=/tmp/outputs
    volumes:
      - ${PWD}/validation/input:/tmp/inputs
      - ${PWD}/validation/output:/tmp/outputs
